spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/esercizio86
    username: root
    password: claudio
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: esercizio-86-api-custom-queries-02
